title: Dev & Design
description: Xueer Zhu Portfolio
author: Xueer Zhu
github: https://github.com/xueerzhu
# about: Client tech. Gameplay and AI
# disqus_shortname: gamejournal
# google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/xueer_zhu"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/xueerzhu/"
    - icon: fa-github
      link: "https://github.com/xueerzhu"

# share:
#   twitter_username: github.io
#   fb_appid: 1749788565247320

urls:
    - text: About
      url: /about/
    - text: Projects
      url: /projects/

url: "https://xueerzhu.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
